QuantumSubInterfaceBinding
::omnetpp::opp_string QuantumSubInterfaceBinding::identity
Referenced by parsimPack, parsimUnpack, getIdentity, setIdentity.
int QuantumSubInterfaceBinding::connectionId
Referenced by parsimPack, parsimUnpack, getConnectionId, setConnectionId.
::omnetpp::opp_string QuantumSubInterfaceBinding::sourceInterface
Referenced by parsimPack, parsimUnpack, getSourceInterface, setSourceInterface.
::omnetpp::opp_string QuantumSubInterfaceBinding::sourceSubInterface
Referenced by parsimPack, parsimUnpack, getSourceSubInterface, setSourceSubInterface.
::omnetpp::opp_string QuantumSubInterfaceBinding::destinationInterface
Referenced by parsimPack, parsimUnpack, getDestinationInterface, setDestinationInterface.
::omnetpp::opp_string QuantumSubInterfaceBinding::destinationSubInterface
Referenced by parsimPack, parsimUnpack, getDestinationSubInterface, setDestinationSubInterface.
int QuantumSubInterfaceBinding::status
Referenced by parsimPack, parsimUnpack, getStatus, setStatus.
void QuantumSubInterfaceBinding::copy(const QuantumSubInterfaceBinding &other)
bool QuantumSubInterfaceBinding::operator==(const QuantumSubInterfaceBinding &)
QuantumSubInterfaceBinding::QuantumSubInterfaceBinding(const char *name=nullptr, short kind=0)
Referenced by dup.
QuantumSubInterfaceBinding::QuantumSubInterfaceBinding(const QuantumSubInterfaceBinding &other)
QuantumSubInterfaceBinding::~QuantumSubInterfaceBinding()
QuantumSubInterfaceBinding & QuantumSubInterfaceBinding::operator=(const QuantumSubInterfaceBinding &other)
virtual QuantumSubInterfaceBinding* QuantumSubInterfaceBinding::dup() const override
References QuantumSubInterfaceBinding.
void QuantumSubInterfaceBinding::parsimPack(omnetpp::cCommBuffer *b) const override
References omnetpp::doParsimPacking, identity, connectionId, sourceInterface, sourceSubInterface, destinationInterface, destinationSubInterface, status.
Referenced by doParsimPacking.
void QuantumSubInterfaceBinding::parsimUnpack(omnetpp::cCommBuffer *b) override
References omnetpp::doParsimUnpacking, identity, connectionId, sourceInterface, sourceSubInterface, destinationInterface, destinationSubInterface, status.
Referenced by doParsimUnpacking.
const char * QuantumSubInterfaceBinding::getIdentity() const
References identity.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString.
void QuantumSubInterfaceBinding::setIdentity(const char *identity)
References identity.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.
int QuantumSubInterfaceBinding::getConnectionId() const
References connectionId.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString.
void QuantumSubInterfaceBinding::setConnectionId(int connectionId)
References connectionId.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.
const char * QuantumSubInterfaceBinding::getSourceInterface() const
References sourceInterface.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString, SwitchMemory::getExitInterfaceFromBindingTable.
void QuantumSubInterfaceBinding::setSourceInterface(const char *sourceInterface)
References sourceInterface.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.
const char * QuantumSubInterfaceBinding::getSourceSubInterface() const
References sourceSubInterface.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString, SwitchMemory::getExitInterfaceFromBindingTable.
void QuantumSubInterfaceBinding::setSourceSubInterface(const char *sourceSubInterface)
References sourceSubInterface.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.
const char * QuantumSubInterfaceBinding::getDestinationInterface() const
References destinationInterface.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString, SwitchMemory::getExitInterfaceFromBindingTable.
void QuantumSubInterfaceBinding::setDestinationInterface(const char *destinationInterface)
References destinationInterface.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.
const char * QuantumSubInterfaceBinding::getDestinationSubInterface() const
References destinationSubInterface.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString.
void QuantumSubInterfaceBinding::setDestinationSubInterface(const char *destinationSubInterface)
References destinationSubInterface.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.
int QuantumSubInterfaceBinding::getStatus() const
References status.
Referenced by Processor::printQuantumSubinterfaceBindingTable, QuantumSubInterfaceBindingDescriptor::getFieldValueAsString.
void QuantumSubInterfaceBinding::setStatus(int status)
References status.
Referenced by Processor::bindSubInterface, QuantumSubInterfaceBindingDescriptor::setFieldValueAsString.