ArpTableEntryDescriptor
const char** ArpTableEntryDescriptor::propertynames
ArpTableEntryDescriptor::ArpTableEntryDescriptor()
ArpTableEntryDescriptor::~ArpTableEntryDescriptor()
bool ArpTableEntryDescriptor::doesSupport(omnetpp::cObject *obj) const override
const char ** ArpTableEntryDescriptor::getPropertyNames() const override
const char * ArpTableEntryDescriptor::getProperty(const char *propertyname) const override
int ArpTableEntryDescriptor::getFieldCount() const override
Referenced by getFieldTypeFlags, getFieldName, getFieldTypeString, getFieldPropertyNames, getFieldProperty, getFieldArraySize, getFieldDynamicTypeString, getFieldValueAsString, setFieldValueAsString, getFieldStructName, getFieldStructValuePointer.
const char * ArpTableEntryDescriptor::getFieldName(int field) const override
References getFieldCount.
int ArpTableEntryDescriptor::findField(const char *fieldName) const override
unsigned int ArpTableEntryDescriptor::getFieldTypeFlags(int field) const override
References getFieldCount.
const char * ArpTableEntryDescriptor::getFieldTypeString(int field) const override
References getFieldCount.
const char ** ArpTableEntryDescriptor::getFieldPropertyNames(int field) const override
References getFieldCount.
const char * ArpTableEntryDescriptor::getFieldProperty(int field, const char *propertyname) const override
References getFieldCount.
int ArpTableEntryDescriptor::getFieldArraySize(void *object, int field) const override
References getFieldCount.
const char * ArpTableEntryDescriptor::getFieldDynamicTypeString(void *object, int field, int i) const override
References getFieldCount.
std::string ArpTableEntryDescriptor::getFieldValueAsString(void *object, int field, int i) const override
References getFieldCount, ArpTableEntry::getIdentity, ArpTableEntry::getProtocol, ArpTableEntry::getIpAddress, ArpTableEntry::getMacAddress, ArpTableEntry::getAge, ArpTableEntry::getType, ArpTableEntry::getInterface.
bool ArpTableEntryDescriptor::setFieldValueAsString(void *object, int field, int i, const char *value) const override
References getFieldCount, ArpTableEntry::setIdentity, ArpTableEntry::setProtocol, ArpTableEntry::setIpAddress, ArpTableEntry::setMacAddress, ArpTableEntry::setAge, ArpTableEntry::setType, ArpTableEntry::setInterface.
const char * ArpTableEntryDescriptor::getFieldStructName(int field) const override
References getFieldCount.
void * ArpTableEntryDescriptor::getFieldStructValuePointer(void *object, int field, int i) const override
References getFieldCount.