MacTableEntryDescriptor
const char** MacTableEntryDescriptor::propertynames
MacTableEntryDescriptor::MacTableEntryDescriptor()
MacTableEntryDescriptor::~MacTableEntryDescriptor()
bool MacTableEntryDescriptor::doesSupport(omnetpp::cObject *obj) const override
const char ** MacTableEntryDescriptor::getPropertyNames() const override
const char * MacTableEntryDescriptor::getProperty(const char *propertyname) const override
int MacTableEntryDescriptor::getFieldCount() const override
Referenced by getFieldTypeFlags, getFieldName, getFieldTypeString, getFieldPropertyNames, getFieldProperty, getFieldArraySize, getFieldDynamicTypeString, getFieldValueAsString, setFieldValueAsString, getFieldStructName, getFieldStructValuePointer.
const char * MacTableEntryDescriptor::getFieldName(int field) const override
References getFieldCount.
int MacTableEntryDescriptor::findField(const char *fieldName) const override
unsigned int MacTableEntryDescriptor::getFieldTypeFlags(int field) const override
References getFieldCount.
const char * MacTableEntryDescriptor::getFieldTypeString(int field) const override
References getFieldCount.
const char ** MacTableEntryDescriptor::getFieldPropertyNames(int field) const override
References getFieldCount.
const char * MacTableEntryDescriptor::getFieldProperty(int field, const char *propertyname) const override
References getFieldCount.
int MacTableEntryDescriptor::getFieldArraySize(void *object, int field) const override
References getFieldCount.
const char * MacTableEntryDescriptor::getFieldDynamicTypeString(void *object, int field, int i) const override
References getFieldCount.
std::string MacTableEntryDescriptor::getFieldValueAsString(void *object, int field, int i) const override
References getFieldCount, MacTableEntry::getIdentity, MacTableEntry::getInterface, MacTableEntry::getMacAddress, MacTableEntry::getQuantumInterfaceId, MacTableEntry::getQuantumMacAddress, MacTableEntry::getType.
bool MacTableEntryDescriptor::setFieldValueAsString(void *object, int field, int i, const char *value) const override
References getFieldCount, MacTableEntry::setIdentity, MacTableEntry::setInterface, MacTableEntry::setMacAddress, MacTableEntry::setQuantumInterfaceId, MacTableEntry::setQuantumMacAddress, MacTableEntry::setType.
const char * MacTableEntryDescriptor::getFieldStructName(int field) const override
References getFieldCount.
void * MacTableEntryDescriptor::getFieldStructValuePointer(void *object, int field, int i) const override
References getFieldCount.