MacTableEntry
int MacTableEntry::identity
Referenced by parsimPack, parsimUnpack, getIdentity, setIdentity.
::omnetpp::opp_string MacTableEntry::interface
Referenced by parsimPack, parsimUnpack, getInterface.
::omnetpp::opp_string MacTableEntry::macAddress
Referenced by parsimPack, parsimUnpack, getMacAddress, setMacAddress.
::omnetpp::opp_string MacTableEntry::quantumInterfaceId
Referenced by parsimPack, parsimUnpack, getQuantumInterfaceId, setQuantumInterfaceId.
::omnetpp::opp_string MacTableEntry::quantumMacAddress
Referenced by parsimPack, parsimUnpack, getQuantumMacAddress, setQuantumMacAddress.
int MacTableEntry::type
Referenced by parsimPack, parsimUnpack, getType, setType.
void MacTableEntry::copy(const MacTableEntry &other)
bool MacTableEntry::operator==(const MacTableEntry &)
MacTableEntry::MacTableEntry(const char *name=nullptr, short kind=0)
Referenced by dup.
MacTableEntry::MacTableEntry(const MacTableEntry &other)
MacTableEntry::~MacTableEntry()
MacTableEntry & MacTableEntry::operator=(const MacTableEntry &other)
virtual MacTableEntry* MacTableEntry::dup() const override
References MacTableEntry.
void MacTableEntry::parsimPack(omnetpp::cCommBuffer *b) const override
References omnetpp::doParsimPacking, identity, interface, macAddress, quantumInterfaceId, quantumMacAddress, type.
Referenced by doParsimPacking.
void MacTableEntry::parsimUnpack(omnetpp::cCommBuffer *b) override
References omnetpp::doParsimUnpacking, identity, interface, macAddress, quantumInterfaceId, quantumMacAddress, type.
Referenced by doParsimUnpacking.
int MacTableEntry::getIdentity() const
References identity.
Referenced by ClientProcessor::printMacTable, MacTableEntryDescriptor::getFieldValueAsString, Processor::printMacAddressTable.
void MacTableEntry::setIdentity(int identity)
References identity.
Referenced by ClientProcessor::initialize, MacTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage, Processor::bindInterface.
const char * MacTableEntry::getInterface() const
References interface.
Referenced by ClientProcessor::printMacTable, MacTableEntryDescriptor::getFieldValueAsString, Processor::printMacAddressTable, SwitchMemory::getInterface.
void MacTableEntry::setInterface(const char *interface)
Referenced by ClientProcessor::initialize, MacTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage, Processor::bindInterface.
const char * MacTableEntry::getMacAddress() const
References macAddress.
Referenced by ClientProcessor::printMacTable, MacTableEntryDescriptor::getFieldValueAsString, Processor::printMacAddressTable, SwitchMemory::getInterface.
void MacTableEntry::setMacAddress(const char *macAddress)
References macAddress.
Referenced by ClientProcessor::initialize, MacTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage, Processor::bindInterface.
const char * MacTableEntry::getQuantumInterfaceId() const
References quantumInterfaceId.
Referenced by ClientProcessor::printMacTable, MacTableEntryDescriptor::getFieldValueAsString, Processor::printMacAddressTable.
void MacTableEntry::setQuantumInterfaceId(const char *quantumInterfaceId)
References quantumInterfaceId.
Referenced by ClientProcessor::initialize, MacTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage, Processor::bindInterface.
const char * MacTableEntry::getQuantumMacAddress() const
References quantumMacAddress.
Referenced by MacTableEntryDescriptor::getFieldValueAsString, Processor::printMacAddressTable.
void MacTableEntry::setQuantumMacAddress(const char *quantumMacAddress)
References quantumMacAddress.
Referenced by MacTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage, Processor::bindInterface.
int MacTableEntry::getType() const
References type.
Referenced by ClientProcessor::printMacTable, MacTableEntryDescriptor::getFieldValueAsString, Processor::printMacAddressTable.
void MacTableEntry::setType(int type)
References type.
Referenced by ClientProcessor::initialize, MacTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage, Processor::bindInterface.