QuantumKeyEntry
int QuantumKeyEntry::identity
Referenced by parsimPack, parsimUnpack, getIdentity, setIdentity.
::omnetpp::opp_string QuantumKeyEntry::macAddress
Referenced by parsimPack, parsimUnpack, getMacAddress, setMacAddress.
::omnetpp::opp_string QuantumKeyEntry::key
Referenced by parsimPack, parsimUnpack, getKey, setKey.
::omnetpp::opp_string QuantumKeyEntry::status
Referenced by parsimPack, parsimUnpack, getStatus, setStatus.
void QuantumKeyEntry::copy(const QuantumKeyEntry &other)
bool QuantumKeyEntry::operator==(const QuantumKeyEntry &)
QuantumKeyEntry::QuantumKeyEntry(const char *name=nullptr, short kind=0)
Referenced by dup.
QuantumKeyEntry::QuantumKeyEntry(const QuantumKeyEntry &other)
QuantumKeyEntry::~QuantumKeyEntry()
QuantumKeyEntry & QuantumKeyEntry::operator=(const QuantumKeyEntry &other)
virtual QuantumKeyEntry* QuantumKeyEntry::dup() const override
References QuantumKeyEntry.
void QuantumKeyEntry::parsimPack(omnetpp::cCommBuffer *b) const override
References omnetpp::doParsimPacking, identity, macAddress, key, status.
Referenced by doParsimPacking.
void QuantumKeyEntry::parsimUnpack(omnetpp::cCommBuffer *b) override
References omnetpp::doParsimUnpacking, identity, macAddress, key, status.
Referenced by doParsimUnpacking.
int QuantumKeyEntry::getIdentity() const
References identity.
Referenced by ClientProcessor::printKeyTable, QuantumKeyEntryDescriptor::getFieldValueAsString.
void QuantumKeyEntry::setIdentity(int identity)
References identity.
Referenced by ClientProcessor::handleMessage, QuantumKeyEntryDescriptor::setFieldValueAsString.
const char * QuantumKeyEntry::getMacAddress() const
References macAddress.
Referenced by ClientMemory::getPendingKeyMacAddress, ClientProcessor::printKeyTable, QuantumKeyEntryDescriptor::getFieldValueAsString.
void QuantumKeyEntry::setMacAddress(const char *macAddress)
References macAddress.
Referenced by ClientProcessor::handleMessage, QuantumKeyEntryDescriptor::setFieldValueAsString.
const char * QuantumKeyEntry::getKey() const
References key.
Referenced by ClientMemory::getPendingTransaction, ClientMemory::setPendingKey, ClientProcessor::printKeyTable, QuantumKeyEntryDescriptor::getFieldValueAsString.
void QuantumKeyEntry::setKey(const char *key)
References key.
Referenced by ClientMemory::setPendingKey, ClientProcessor::handleMessage, QuantumKeyEntryDescriptor::setFieldValueAsString.
const char * QuantumKeyEntry::getStatus() const
References status.
Referenced by ClientMemory::getPendingKeyMacAddress, ClientProcessor::printKeyTable, QuantumKeyEntryDescriptor::getFieldValueAsString.
void QuantumKeyEntry::setStatus(const char *status)
References status.
Referenced by ClientMemory::getPendingKeyMacAddress, ClientProcessor::handleMessage, QuantumKeyEntryDescriptor::setFieldValueAsString.