SessionStateEntry
int SessionStateEntry::sessionId
Referenced by parsimPack, parsimUnpack, getSessionId, setSessionId.
::omnetpp::opp_string SessionStateEntry::srcMac
Referenced by parsimPack, parsimUnpack, getSrcMac, setSrcMac.
::omnetpp::opp_string SessionStateEntry::srcQMac
Referenced by parsimPack, parsimUnpack, getSrcQMac, setSrcQMac.
::omnetpp::opp_string SessionStateEntry::srcSubInterface
Referenced by parsimPack, parsimUnpack, getSrcSubInterface, setSrcSubInterface.
::omnetpp::opp_string SessionStateEntry::desMac
Referenced by parsimPack, parsimUnpack, getDesMac, setDesMac.
::omnetpp::opp_string SessionStateEntry::desQMac
Referenced by parsimPack, parsimUnpack, getDesQMac, setDesQMac.
::omnetpp::opp_string SessionStateEntry::desSubInterface
Referenced by parsimPack, parsimUnpack, getDesSubInterface, setDesSubInterface.
::omnetpp::opp_string SessionStateEntry::expiry
Referenced by parsimPack, parsimUnpack, getExpiry, setExpiry.
::omnetpp::opp_string SessionStateEntry::status
Referenced by parsimPack, parsimUnpack, getStatus, setStatus.
void SessionStateEntry::copy(const SessionStateEntry &other)
bool SessionStateEntry::operator==(const SessionStateEntry &)
SessionStateEntry::SessionStateEntry(const char *name=nullptr, short kind=0)
Referenced by dup.
SessionStateEntry::SessionStateEntry(const SessionStateEntry &other)
SessionStateEntry::~SessionStateEntry()
SessionStateEntry & SessionStateEntry::operator=(const SessionStateEntry &other)
virtual SessionStateEntry* SessionStateEntry::dup() const override
References SessionStateEntry.
void SessionStateEntry::parsimPack(omnetpp::cCommBuffer *b) const override
References omnetpp::doParsimPacking, sessionId, srcMac, srcQMac, srcSubInterface, desMac, desQMac, desSubInterface, expiry, status.
Referenced by doParsimPacking.
void SessionStateEntry::parsimUnpack(omnetpp::cCommBuffer *b) override
References omnetpp::doParsimUnpacking, sessionId, srcMac, srcQMac, srcSubInterface, desMac, desQMac, desSubInterface, expiry, status.
Referenced by doParsimUnpacking.
int SessionStateEntry::getSessionId() const
References sessionId.
Referenced by Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setSessionId(int sessionId)
References sessionId.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getSrcMac() const
References srcMac.
Referenced by Processor::handleMessage, Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString, SwitchMemory::entryExist.
void SessionStateEntry::setSrcMac(const char *srcMac)
References srcMac.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getSrcQMac() const
References srcQMac.
Referenced by Processor::handleMessage, Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setSrcQMac(const char *srcQMac)
References srcQMac.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getSrcSubInterface() const
References srcSubInterface.
Referenced by Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setSrcSubInterface(const char *srcSubInterface)
References srcSubInterface.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getDesMac() const
References desMac.
Referenced by Processor::handleMessage, Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString, SwitchMemory::entryExist.
void SessionStateEntry::setDesMac(const char *desMac)
References desMac.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getDesQMac() const
References desQMac.
Referenced by Processor::handleMessage, Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setDesQMac(const char *desQMac)
References desQMac.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getDesSubInterface() const
References desSubInterface.
Referenced by Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setDesSubInterface(const char *desSubInterface)
References desSubInterface.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getExpiry() const
References expiry.
Referenced by Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setExpiry(const char *expiry)
References expiry.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.
const char * SessionStateEntry::getStatus() const
References status.
Referenced by Processor::printSessionStateTable, SessionStateEntryDescriptor::getFieldValueAsString.
void SessionStateEntry::setStatus(const char *status)
References status.
Referenced by Processor::handleMessage, SessionStateEntryDescriptor::setFieldValueAsString.