ArpTableEntry
int ArpTableEntry::identity
Referenced by parsimPack, parsimUnpack, getIdentity, setIdentity.
::omnetpp::opp_string ArpTableEntry::protocol
Referenced by parsimPack, parsimUnpack, getProtocol, setProtocol.
::omnetpp::opp_string ArpTableEntry::ipAddress
Referenced by parsimPack, parsimUnpack, getIpAddress, setIpAddress.
::omnetpp::opp_string ArpTableEntry::macAddress
Referenced by parsimPack, parsimUnpack, getMacAddress, setMacAddress.
::omnetpp::opp_string ArpTableEntry::age
Referenced by parsimPack, parsimUnpack, getAge, setAge.
int ArpTableEntry::type
Referenced by parsimPack, parsimUnpack, getType, setType.
::omnetpp::opp_string ArpTableEntry::interface
Referenced by parsimPack, parsimUnpack, getInterface.
void ArpTableEntry::copy(const ArpTableEntry &other)
bool ArpTableEntry::operator==(const ArpTableEntry &)
ArpTableEntry::ArpTableEntry(const char *name=nullptr, short kind=0)
Referenced by dup.
ArpTableEntry::ArpTableEntry(const ArpTableEntry &other)
ArpTableEntry::~ArpTableEntry()
ArpTableEntry & ArpTableEntry::operator=(const ArpTableEntry &other)
virtual ArpTableEntry* ArpTableEntry::dup() const override
References ArpTableEntry.
void ArpTableEntry::parsimPack(omnetpp::cCommBuffer *b) const override
References omnetpp::doParsimPacking, identity, protocol, ipAddress, macAddress, age, type, interface.
Referenced by doParsimPacking.
void ArpTableEntry::parsimUnpack(omnetpp::cCommBuffer *b) override
References omnetpp::doParsimUnpacking, identity, protocol, ipAddress, macAddress, age, type, interface.
Referenced by doParsimUnpacking.
int ArpTableEntry::getIdentity() const
References identity.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setIdentity(int identity)
References identity.
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.
const char * ArpTableEntry::getProtocol() const
References protocol.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setProtocol(const char *protocol)
References protocol.
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.
const char * ArpTableEntry::getIpAddress() const
References ipAddress.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setIpAddress(const char *ipAddress)
References ipAddress.
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.
const char * ArpTableEntry::getMacAddress() const
References macAddress.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setMacAddress(const char *macAddress)
References macAddress.
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.
const char * ArpTableEntry::getAge() const
References age.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setAge(const char *age)
References age.
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.
int ArpTableEntry::getType() const
References type.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setType(int type)
References type.
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.
const char * ArpTableEntry::getInterface() const
References interface.
Referenced by ArpTableEntryDescriptor::getFieldValueAsString, Processor::printArpTable.
void ArpTableEntry::setInterface(const char *interface)
Referenced by ArpTableEntryDescriptor::setFieldValueAsString, Processor::handleMessage.