SessionStateEntryDescriptor
const char** SessionStateEntryDescriptor::propertynames
SessionStateEntryDescriptor::SessionStateEntryDescriptor()
SessionStateEntryDescriptor::~SessionStateEntryDescriptor()
bool SessionStateEntryDescriptor::doesSupport(omnetpp::cObject *obj) const override
const char ** SessionStateEntryDescriptor::getPropertyNames() const override
const char * SessionStateEntryDescriptor::getProperty(const char *propertyname) const override
int SessionStateEntryDescriptor::getFieldCount() const override
Referenced by getFieldTypeFlags, getFieldName, getFieldTypeString, getFieldPropertyNames, getFieldProperty, getFieldArraySize, getFieldDynamicTypeString, getFieldValueAsString, setFieldValueAsString, getFieldStructName, getFieldStructValuePointer.
const char * SessionStateEntryDescriptor::getFieldName(int field) const override
References getFieldCount.
int SessionStateEntryDescriptor::findField(const char *fieldName) const override
unsigned int SessionStateEntryDescriptor::getFieldTypeFlags(int field) const override
References getFieldCount.
const char * SessionStateEntryDescriptor::getFieldTypeString(int field) const override
References getFieldCount.
const char ** SessionStateEntryDescriptor::getFieldPropertyNames(int field) const override
References getFieldCount.
const char * SessionStateEntryDescriptor::getFieldProperty(int field, const char *propertyname) const override
References getFieldCount.
int SessionStateEntryDescriptor::getFieldArraySize(void *object, int field) const override
References getFieldCount.
const char * SessionStateEntryDescriptor::getFieldDynamicTypeString(void *object, int field, int i) const override
References getFieldCount.
std::string SessionStateEntryDescriptor::getFieldValueAsString(void *object, int field, int i) const override
References getFieldCount, SessionStateEntry::getSessionId, SessionStateEntry::getSrcMac, SessionStateEntry::getSrcQMac, SessionStateEntry::getSrcSubInterface, SessionStateEntry::getDesMac, SessionStateEntry::getDesQMac, SessionStateEntry::getDesSubInterface, SessionStateEntry::getExpiry, SessionStateEntry::getStatus.
bool SessionStateEntryDescriptor::setFieldValueAsString(void *object, int field, int i, const char *value) const override
References getFieldCount, SessionStateEntry::setSessionId, SessionStateEntry::setSrcMac, SessionStateEntry::setSrcQMac, SessionStateEntry::setSrcSubInterface, SessionStateEntry::setDesMac, SessionStateEntry::setDesQMac, SessionStateEntry::setDesSubInterface, SessionStateEntry::setExpiry, SessionStateEntry::setStatus.
const char * SessionStateEntryDescriptor::getFieldStructName(int field) const override
References getFieldCount.
void * SessionStateEntryDescriptor::getFieldStructValuePointer(void *object, int field, int i) const override
References getFieldCount.