QuantumSubInterfaceBindingDescriptor
const char** QuantumSubInterfaceBindingDescriptor::propertynames
QuantumSubInterfaceBindingDescriptor::QuantumSubInterfaceBindingDescriptor()
QuantumSubInterfaceBindingDescriptor::~QuantumSubInterfaceBindingDescriptor()
bool QuantumSubInterfaceBindingDescriptor::doesSupport(omnetpp::cObject *obj) const override
const char ** QuantumSubInterfaceBindingDescriptor::getPropertyNames() const override
const char * QuantumSubInterfaceBindingDescriptor::getProperty(const char *propertyname) const override
int QuantumSubInterfaceBindingDescriptor::getFieldCount() const override
Referenced by getFieldTypeFlags, getFieldName, getFieldTypeString, getFieldPropertyNames, getFieldProperty, getFieldArraySize, getFieldDynamicTypeString, getFieldValueAsString, setFieldValueAsString, getFieldStructName, getFieldStructValuePointer.
const char * QuantumSubInterfaceBindingDescriptor::getFieldName(int field) const override
References getFieldCount.
int QuantumSubInterfaceBindingDescriptor::findField(const char *fieldName) const override
unsigned int QuantumSubInterfaceBindingDescriptor::getFieldTypeFlags(int field) const override
References getFieldCount.
const char * QuantumSubInterfaceBindingDescriptor::getFieldTypeString(int field) const override
References getFieldCount.
const char ** QuantumSubInterfaceBindingDescriptor::getFieldPropertyNames(int field) const override
References getFieldCount.
const char * QuantumSubInterfaceBindingDescriptor::getFieldProperty(int field, const char *propertyname) const override
References getFieldCount.
int QuantumSubInterfaceBindingDescriptor::getFieldArraySize(void *object, int field) const override
References getFieldCount.
const char * QuantumSubInterfaceBindingDescriptor::getFieldDynamicTypeString(void *object, int field, int i) const override
References getFieldCount.
std::string QuantumSubInterfaceBindingDescriptor::getFieldValueAsString(void *object, int field, int i) const override
References getFieldCount, QuantumSubInterfaceBinding::getIdentity, QuantumSubInterfaceBinding::getConnectionId, QuantumSubInterfaceBinding::getSourceInterface, QuantumSubInterfaceBinding::getSourceSubInterface, QuantumSubInterfaceBinding::getDestinationInterface, QuantumSubInterfaceBinding::getDestinationSubInterface, QuantumSubInterfaceBinding::getStatus.
bool QuantumSubInterfaceBindingDescriptor::setFieldValueAsString(void *object, int field, int i, const char *value) const override
References getFieldCount, QuantumSubInterfaceBinding::setIdentity, QuantumSubInterfaceBinding::setConnectionId, QuantumSubInterfaceBinding::setSourceInterface, QuantumSubInterfaceBinding::setSourceSubInterface, QuantumSubInterfaceBinding::setDestinationInterface, QuantumSubInterfaceBinding::setDestinationSubInterface, QuantumSubInterfaceBinding::setStatus.
const char * QuantumSubInterfaceBindingDescriptor::getFieldStructName(int field) const override
References getFieldCount.
void * QuantumSubInterfaceBindingDescriptor::getFieldStructValuePointer(void *object, int field, int i) const override
References getFieldCount.