QuantumKeyEntryDescriptor
const char** QuantumKeyEntryDescriptor::propertynames
QuantumKeyEntryDescriptor::QuantumKeyEntryDescriptor()
QuantumKeyEntryDescriptor::~QuantumKeyEntryDescriptor()
bool QuantumKeyEntryDescriptor::doesSupport(omnetpp::cObject *obj) const override
const char ** QuantumKeyEntryDescriptor::getPropertyNames() const override
const char * QuantumKeyEntryDescriptor::getProperty(const char *propertyname) const override
int QuantumKeyEntryDescriptor::getFieldCount() const override
Referenced by getFieldTypeFlags, getFieldName, getFieldTypeString, getFieldPropertyNames, getFieldProperty, getFieldArraySize, getFieldDynamicTypeString, getFieldValueAsString, setFieldValueAsString, getFieldStructName, getFieldStructValuePointer.
const char * QuantumKeyEntryDescriptor::getFieldName(int field) const override
References getFieldCount.
int QuantumKeyEntryDescriptor::findField(const char *fieldName) const override
unsigned int QuantumKeyEntryDescriptor::getFieldTypeFlags(int field) const override
References getFieldCount.
const char * QuantumKeyEntryDescriptor::getFieldTypeString(int field) const override
References getFieldCount.
const char ** QuantumKeyEntryDescriptor::getFieldPropertyNames(int field) const override
References getFieldCount.
const char * QuantumKeyEntryDescriptor::getFieldProperty(int field, const char *propertyname) const override
References getFieldCount.
int QuantumKeyEntryDescriptor::getFieldArraySize(void *object, int field) const override
References getFieldCount.
const char * QuantumKeyEntryDescriptor::getFieldDynamicTypeString(void *object, int field, int i) const override
References getFieldCount.
std::string QuantumKeyEntryDescriptor::getFieldValueAsString(void *object, int field, int i) const override
References getFieldCount, QuantumKeyEntry::getIdentity, QuantumKeyEntry::getMacAddress, QuantumKeyEntry::getKey, QuantumKeyEntry::getStatus.
bool QuantumKeyEntryDescriptor::setFieldValueAsString(void *object, int field, int i, const char *value) const override
References getFieldCount, QuantumKeyEntry::setIdentity, QuantumKeyEntry::setMacAddress, QuantumKeyEntry::setKey, QuantumKeyEntry::setStatus.
const char * QuantumKeyEntryDescriptor::getFieldStructName(int field) const override
References getFieldCount.
void * QuantumKeyEntryDescriptor::getFieldStructValuePointer(void *object, int field, int i) const override
References getFieldCount.