ClientMemory
cArray ClientMemory::quantumTable
cArray ClientMemory::quantumKey
std::string ClientMemory::initialKey
std::string ClientMemory::initialKeyBin
std::string ClientMemory::polarizationStates
MacTableEntry ClientMemory::getMacTable(int index)
Referenced by ClientProcessor::printMacTable.
void ClientMemory::addMacTableEntry(MacTableEntry *macTableEntry)
Referenced by ClientProcessor::initialize.
int ClientMemory::getMacTableSize()
QuantumKeyEntry ClientMemory::getQuantumKey(int index)
Referenced by ClientProcessor::handleMessage, ClientProcessor::printKeyTable.
void ClientMemory::addQautumKey(QuantumKeyEntry *key)
Referenced by ClientProcessor::handleMessage.
int ClientMemory::getNumberOfKey()
Referenced by ClientProcessor::printKeyTable.
int ClientMemory::getPendingTransaction()
References QuantumKeyEntry::getKey.
Referenced by ClientProcessor::handleMessage.
std::string ClientMemory::getPendingKeyMacAddress()
References QuantumKeyEntry::getStatus, QuantumKeyEntry::getMacAddress, QuantumKeyEntry::setStatus.
Referenced by ClientProcessor::handleMessage.
void ClientMemory::setPendingKey(std::string key)
References QuantumKeyEntry::getKey, QuantumKeyEntry::setKey.
Referenced by ClientProcessor::handleMessage.
std::string ClientMemory::getInitialKey()
void ClientMemory::setInitialKey(std::string key)
std::string ClientMemory::getPolarizationStates()
Referenced by ClientProcessor::handleMessage.
void ClientMemory::setPolarizationStates(std::string states)
Referenced by ClientProcessor::handleMessage.
std::string ClientMemory::getInitialKeyBin()
Referenced by ClientProcessor::handleMessage.
void ClientMemory::setInitialKeyBin(std::string bin)
Referenced by ClientProcessor::handleMessage.
void ClientMemory::initialize()
void ClientMemory::handleMessage(cMessage *msg)