ClientProcessor
void ClientProcessor::initialize(int stage) override
References MacTableEntry::setIdentity, MacTableEntry::setInterface, MacTableEntry::setMacAddress, MacTableEntry::setQuantumInterfaceId, MacTableEntry::setType, ClientMemory::addMacTableEntry, printMacTable.
void ClientProcessor::handleMessage(cMessage *msg) override
References QuantumKeyEntry::setIdentity, QuantumKeyEntry::setMacAddress, ClientMemory::addQautumKey, printKeyTable, ClientMemory::setInitialKeyBin, convertToBinary, ClientMemory::getInitialKeyBin, QuantumKeyEntry::setKey, compareBasis, ClientMemory::getPolarizationStates, QuantumKeyEntry::setStatus, ClientMemory::setPendingKey, ClientMemory::getQuantumKey, ClientMemory::getPendingTransaction, ClientMemory::getPendingKeyMacAddress, ClientMemory::setPolarizationStates.
int ClientProcessor::numInitStages() const override
unsigned int ClientProcessor::countSetBits(unsigned int n)
std::string ClientProcessor::generateRandomKey(int keyLength)
std::string ClientProcessor::convertToBinary(int initialKey)
Referenced by handleMessage.
std::string ClientProcessor::compareBasis(std::string statesUsed, std::string receivedStates, std::string randomBits)
Referenced by handleMessage.
void ClientProcessor::initializeNetwork()
void ClientProcessor::initiateQKDRequest(std::string source, std::string destination)
void ClientProcessor::printMacTable()
References ClientMemory::getMacTable, MacTableEntry::getIdentity, MacTableEntry::getInterface, MacTableEntry::getMacAddress, MacTableEntry::getQuantumInterfaceId, MacTableEntry::getType.
Referenced by initialize.
void ClientProcessor::printKeyTable()
References ClientMemory::getNumberOfKey, ClientMemory::getQuantumKey, QuantumKeyEntry::getMacAddress, QuantumKeyEntry::getIdentity, QuantumKeyEntry::getKey, QuantumKeyEntry::getStatus.
Referenced by handleMessage.