SwitchMemory
cArray SwitchMemory::macAddressTable
cArray SwitchMemory::quantumSubInterfaceBinding
cArray SwitchMemory::arpTable
cArray SwitchMemory::sessionStateTable
int SwitchMemory::macEntryIndex
Referenced by Processor::initialize, Processor::handleMessage, Processor::prepareMacAddressTable.
int SwitchMemory::quantumBindingEntryIndex
int SwitchMemory::arpEntryIndex
Referenced by Processor::initialize, Processor::handleMessage.
int SwitchMemory::sessionsStateEntryIndex
Referenced by Processor::initialize, Processor::handleMessage.
std::string SwitchMemory::searchMacAddressTableByMacAddress(std::string macAddress, char query)
std::string SwitchMemory::searchMacAddressTableByInterface(std::string interface, char query)
std::string SwitchMemory::searchMacAddressTableByQuantumMacAddress(std::string interface, char query)
std::string SwitchMemory::searchSessionStateTable(QueryType searchBy, std::string searchValue, char returnValue)
MacTableEntry SwitchMemory::getMacTable(int index)
Referenced by Processor::printMacAddressTable.
void SwitchMemory::addMacTableEntry(MacTableEntry *macTableEntry)
Referenced by Processor::handleMessage, Processor::bindInterface.
int SwitchMemory::getMacTableSize()
Referenced by Processor::printMacAddressTable.
std::string SwitchMemory::getQuantumInterfaceMacAddressFromMacTable(std::string publicInterfaceMacAddress)
Referenced by Processor::handleMessage.
std::string SwitchMemory::getInterfaceIdFromMacTable(std::string macAddress)
References macAddress.
Referenced by Processor::handleMessage.
std::string SwitchMemory::getMacAddressOfInterfaceFromMacTable(std::string interface)
References interface.
Referenced by Processor::handleMessage.
std::string SwitchMemory::getQuantumMacAddressOfInterfaceFromMacTable(std::string interface)
References interface.
Referenced by Processor::handleMessage.
std::string SwitchMemory::getQuantumInterfaceFromMacTable(std::string qMacAddress)
Referenced by Processor::handleMessage.
std::string SwitchMemory::getQuantumInterfaceFromMacTableByPublicMac(std::string macAddress)
References macAddress.
Referenced by Processor::handleMessage.
std::string SwitchMemory::getInterface(std::string macAddress)
References MacTableEntry::getMacAddress, macAddress, MacTableEntry::getInterface.
Referenced by Processor::handleMessage.
bool SwitchMemory::entryExist(std::string srcMac, std::string desMac)
References SessionStateEntry::getSrcMac, SessionStateEntry::getDesMac.
Referenced by Processor::handleMessage.
QuantumSubInterfaceBinding SwitchMemory::getQuantumBindingTable(int index)
Referenced by Processor::printQuantumSubinterfaceBindingTable.
void SwitchMemory::addQuantumBindingTableEntry(QuantumSubInterfaceBinding *quantumBindingEntry)
Referenced by Processor::bindSubInterface.
int SwitchMemory::getQuantumBindingTableSize()
Referenced by Processor::printQuantumSubinterfaceBindingTable.
std::string SwitchMemory::getExitInterfaceFromBindingTable(std::string src, std::string des)
References QuantumSubInterfaceBinding::getSourceInterface, QuantumSubInterfaceBinding::getDestinationInterface, QuantumSubInterfaceBinding::getSourceSubInterface.
Referenced by Processor::handleMessage.
ArpTableEntry SwitchMemory::getArpTableEntry(int index)
Referenced by Processor::printArpTable.
void SwitchMemory::addArpTableEntry(ArpTableEntry *arpTableEntry)
Referenced by Processor::handleMessage.
int SwitchMemory::getArpTableSize()
Referenced by Processor::printArpTable.
SessionStateEntry SwitchMemory::getsessionStateTableEntry(int index)
Referenced by Processor::printSessionStateTable.
void SwitchMemory::addSessionStateTableEntry(SessionStateEntry *sessionStateEntry)
Referenced by Processor::handleMessage.
int SwitchMemory::getSessionStateTableSize()
Referenced by Processor::printSessionStateTable.
void SwitchMemory::initialize(int stage) override
int SwitchMemory::numInitStages() const override