Processor
void Processor::initialize(int stage) override
References tModule, switchMemory, SwitchMemory::macEntryIndex, SwitchMemory::arpEntryIndex, SwitchMemory::sessionsStateEntryIndex, prepareQuantumSubInterfaceBindingTable, printQuantumSubinterfaceBindingTable, prepareMacAddressTable, printMacAddressTable.
void Processor::handleMessage(cMessage *msg) override
References MacTableEntry::setIdentity, switchMemory, SwitchMemory::macEntryIndex, MacTableEntry::setInterface, MacTableEntry::setMacAddress, MacTableEntry::setQuantumInterfaceId, MacTableEntry::setQuantumMacAddress, MacTableEntry::setType, SwitchMemory::addMacTableEntry, ArpTableEntry::setIdentity, SwitchMemory::arpEntryIndex, ArpTableEntry::setProtocol, ArpTableEntry::setIpAddress, ArpTableEntry::setAge, ArpTableEntry::setMacAddress, ArpTableEntry::setType, ArpTableEntry::setInterface, SwitchMemory::addArpTableEntry, SessionStateEntry::setSessionId, SwitchMemory::sessionsStateEntryIndex, SessionStateEntry::setSrcMac, SessionStateEntry::setSrcQMac, SwitchMemory::getQuantumInterfaceMacAddressFromMacTable, SessionStateEntry::getSrcMac, SessionStateEntry::setSrcSubInterface, SwitchMemory::getQuantumInterfaceFromMacTable, SessionStateEntry::getSrcQMac, SessionStateEntry::setDesMac, SwitchMemory::getMacAddressOfInterfaceFromMacTable, SwitchMemory::getInterfaceIdFromMacTable, SessionStateEntry::setDesQMac, SwitchMemory::getQuantumMacAddressOfInterfaceFromMacTable, SessionStateEntry::setDesSubInterface, SessionStateEntry::getDesQMac, SessionStateEntry::setExpiry, SessionStateEntry::setStatus, SwitchMemory::entryExist, SessionStateEntry::getDesMac, SwitchMemory::addSessionStateTableEntry, SwitchMemory::getQuantumInterfaceFromMacTableByPublicMac, SwitchMemory::getExitInterfaceFromBindingTable, SwitchMemory::getInterface.
int Processor::numInitStages() const override
void Processor::finish() override
References printMacAddressTable, printArpTable, printSessionStateTable.
void Processor::prepareMacAddressTable()
References bindInterface, switchMemory, SwitchMemory::macEntryIndex.
Referenced by initialize.
void Processor::bindInterface(int identity, std::string interface, std::string quantumInterface, int type)
References MacTableEntry::setIdentity, MacTableEntry::setInterface, interface, MacTableEntry::setMacAddress, MacTableEntry::setQuantumInterfaceId, MacTableEntry::setQuantumMacAddress, MacTableEntry::setType, switchMemory, SwitchMemory::addMacTableEntry.
Referenced by prepareMacAddressTable.
void Processor::prepareQuantumSubInterfaceBindingTable()
References bindSubInterface.
Referenced by initialize.
void Processor::bindSubInterface(std::string identity, std::string sourceInterface, std::string sourceSubInterface, std::string destinationInterface, std::string destinationSubInterface, int status)
References QuantumSubInterfaceBinding::setIdentity, QuantumSubInterfaceBinding::setConnectionId, QuantumSubInterfaceBinding::setSourceInterface, QuantumSubInterfaceBinding::setSourceSubInterface, QuantumSubInterfaceBinding::setDestinationInterface, QuantumSubInterfaceBinding::setDestinationSubInterface, QuantumSubInterfaceBinding::setStatus, switchMemory, SwitchMemory::addQuantumBindingTableEntry.
Referenced by prepareQuantumSubInterfaceBindingTable.
void Processor::printMacAddressTable()
References switchMemory, SwitchMemory::getMacTableSize, SwitchMemory::getMacTable, MacTableEntry::getIdentity, MacTableEntry::getInterface, MacTableEntry::getMacAddress, MacTableEntry::getQuantumInterfaceId, MacTableEntry::getQuantumMacAddress, MacTableEntry::getType.
Referenced by initialize, finish.
void Processor::printQuantumSubinterfaceBindingTable()
References switchMemory, SwitchMemory::getQuantumBindingTableSize, SwitchMemory::getQuantumBindingTable, QuantumSubInterfaceBinding::getIdentity, QuantumSubInterfaceBinding::getConnectionId, QuantumSubInterfaceBinding::getSourceInterface, QuantumSubInterfaceBinding::getSourceSubInterface, QuantumSubInterfaceBinding::getDestinationInterface, QuantumSubInterfaceBinding::getDestinationSubInterface, QuantumSubInterfaceBinding::getStatus.
Referenced by initialize.
void Processor::printArpTable()
References switchMemory, SwitchMemory::getArpTableSize, SwitchMemory::getArpTableEntry, ArpTableEntry::getIdentity, ArpTableEntry::getProtocol, ArpTableEntry::getIpAddress, ArpTableEntry::getAge, ArpTableEntry::getMacAddress, ArpTableEntry::getType, ArpTableEntry::getInterface.
Referenced by finish.
void Processor::printSessionStateTable()
References switchMemory, SwitchMemory::getSessionStateTableSize, SwitchMemory::getsessionStateTableEntry, SessionStateEntry::getSessionId, SessionStateEntry::getSrcMac, SessionStateEntry::getSrcQMac, SessionStateEntry::getSrcSubInterface, SessionStateEntry::getDesMac, SessionStateEntry::getDesQMac, SessionStateEntry::getDesSubInterface, SessionStateEntry::getExpiry, SessionStateEntry::getStatus.
Referenced by finish.