omnetpp
void omnetpp::doParsimPacking(omnetpp::cCommBuffer *buffer, const std::vector< T, A > &v)
Referenced by doParsimPacking, doParsimArrayPacking, MacTableEntry::parsimPack, QuantumKeyEntry::parsimPack, QuantumSubInterfaceBinding::parsimPack, SessionStateEntry::parsimPack.
void omnetpp::doParsimUnpacking(omnetpp::cCommBuffer *buffer, std::vector< T, A > &v)
Referenced by doParsimUnpacking, doParsimArrayUnpacking, MacTableEntry::parsimUnpack, QuantumKeyEntry::parsimUnpack, QuantumSubInterfaceBinding::parsimUnpack, SessionStateEntry::parsimUnpack.
void omnetpp::doParsimPacking(omnetpp::cCommBuffer *buffer, const std::list< T, A > &l)
References doParsimPacking.
void omnetpp::doParsimUnpacking(omnetpp::cCommBuffer *buffer, std::list< T, A > &l)
References doParsimUnpacking.
void omnetpp::doParsimPacking(omnetpp::cCommBuffer *buffer, const std::set< T, Tr, A > &s)
References doParsimPacking.
void omnetpp::doParsimUnpacking(omnetpp::cCommBuffer *buffer, std::set< T, Tr, A > &s)
References doParsimUnpacking.
void omnetpp::doParsimPacking(omnetpp::cCommBuffer *buffer, const std::map< K, V, Tr, A > &m)
References doParsimPacking.
void omnetpp::doParsimUnpacking(omnetpp::cCommBuffer *buffer, std::map< K, V, Tr, A > &m)
References doParsimUnpacking.
void omnetpp::doParsimArrayPacking(omnetpp::cCommBuffer *b, const T *t, int n)
References doParsimPacking.
void omnetpp::doParsimArrayUnpacking(omnetpp::cCommBuffer *b, T *t, int n)
References doParsimUnpacking.
void omnetpp::doParsimPacking(omnetpp::cCommBuffer *, const T &t)
Referenced by ArpTableEntry::parsimPack.
void omnetpp::doParsimUnpacking(omnetpp::cCommBuffer *, T &t)
Referenced by ArpTableEntry::parsimUnpack.