//
// Generated file, do not edit! Created by nedtool 5.4 from MacTableEntry.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MACTABLEENTRY_M_H
#define __MACTABLEENTRY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>MacTableEntry.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet MacTableEntry
 * {
 *     int identity;
 *     string interface;
 *     string macAddress;
 *     string quantumInterfaceId;
 *     string quantumMacAddress;
 *     int type;
 * }
 * </pre>
 */
class MacTableEntry : public ::omnetpp::cPacket
{
  protected:
    int identity;
    ::omnetpp::opp_string interface;
    ::omnetpp::opp_string macAddress;
    ::omnetpp::opp_string quantumInterfaceId;
    ::omnetpp::opp_string quantumMacAddress;
    int type;

  private:
    void copy(const MacTableEntry& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacTableEntry&);

  public:
    MacTableEntry(const char *name=nullptr, short kind=0);
    MacTableEntry(const MacTableEntry& other);
    virtual ~MacTableEntry();
    MacTableEntry& operator=(const MacTableEntry& other);
    virtual MacTableEntry *dup() const override {return new MacTableEntry(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getIdentity() const;
    virtual void setIdentity(int identity);
    virtual const char * getInterface() const;
    virtual void setInterface(const char * interface);
    virtual const char * getMacAddress() const;
    virtual void setMacAddress(const char * macAddress);
    virtual const char * getQuantumInterfaceId() const;
    virtual void setQuantumInterfaceId(const char * quantumInterfaceId);
    virtual const char * getQuantumMacAddress() const;
    virtual void setQuantumMacAddress(const char * quantumMacAddress);
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacTableEntry& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacTableEntry& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MACTABLEENTRY_M_H

