//
// Generated file, do not edit! Created by nedtool 5.4 from QuantumSubInterfaceBinding.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __QUANTUMSUBINTERFACEBINDING_M_H
#define __QUANTUMSUBINTERFACEBINDING_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>QuantumSubInterfaceBinding.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet QuantumSubInterfaceBinding
 * {
 *     int identity;
 *     string sourceInterface;
 *     string destinationInterface;
 *     int status;
 * }
 * </pre>
 */
class QuantumSubInterfaceBinding : public ::omnetpp::cPacket
{
  protected:
    int identity;
    ::omnetpp::opp_string sourceInterface;
    ::omnetpp::opp_string destinationInterface;
    int status;

  private:
    void copy(const QuantumSubInterfaceBinding& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QuantumSubInterfaceBinding&);

  public:
    QuantumSubInterfaceBinding(const char *name=nullptr, short kind=0);
    QuantumSubInterfaceBinding(const QuantumSubInterfaceBinding& other);
    virtual ~QuantumSubInterfaceBinding();
    QuantumSubInterfaceBinding& operator=(const QuantumSubInterfaceBinding& other);
    virtual QuantumSubInterfaceBinding *dup() const override {return new QuantumSubInterfaceBinding(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getIdentity() const;
    virtual void setIdentity(int identity);
    virtual const char * getSourceInterface() const;
    virtual void setSourceInterface(const char * sourceInterface);
    virtual const char * getDestinationInterface() const;
    virtual void setDestinationInterface(const char * destinationInterface);
    virtual int getStatus() const;
    virtual void setStatus(int status);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QuantumSubInterfaceBinding& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QuantumSubInterfaceBinding& obj) {obj.parsimUnpack(b);}


#endif // ifndef __QUANTUMSUBINTERFACEBINDING_M_H

