.TH "ArpTableEntry" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArpTableEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ArpTableEntry_m\&.h>\fP
.PP
Inherits cPacket\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArpTableEntry\fP (const char *name=nullptr, short kind=0)"
.br
.ti -1c
.RI "\fBArpTableEntry\fP (const \fBArpTableEntry\fP &other)"
.br
.ti -1c
.RI "virtual \fB~ArpTableEntry\fP ()"
.br
.ti -1c
.RI "\fBArpTableEntry\fP & \fBoperator=\fP (const \fBArpTableEntry\fP &other)"
.br
.ti -1c
.RI "virtual \fBArpTableEntry\fP * \fBdup\fP () const override"
.br
.ti -1c
.RI "virtual void \fBparsimPack\fP (omnetpp::cCommBuffer *b) const override"
.br
.ti -1c
.RI "virtual void \fBparsimUnpack\fP (omnetpp::cCommBuffer *b) override"
.br
.ti -1c
.RI "virtual int \fBgetIdentity\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetIdentity\fP (int \fBidentity\fP)"
.br
.ti -1c
.RI "virtual const char * \fBgetProtocol\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetProtocol\fP (const char *\fBprotocol\fP)"
.br
.ti -1c
.RI "virtual const char * \fBgetIpAddress\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetIpAddress\fP (const char *\fBipAddress\fP)"
.br
.ti -1c
.RI "virtual const char * \fBgetMacAddress\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetMacAddress\fP (const char *\fBmacAddress\fP)"
.br
.ti -1c
.RI "virtual const char * \fBgetAge\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetAge\fP (const char *\fBage\fP)"
.br
.ti -1c
.RI "virtual int \fBgetType\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetType\fP (int \fBtype\fP)"
.br
.ti -1c
.RI "virtual const char * \fBgetInterface\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetInterface\fP (const char *\fBinterface\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBArpTableEntry\fP &)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBidentity\fP"
.br
.ti -1c
.RI "::omnetpp::opp_string \fBprotocol\fP"
.br
.ti -1c
.RI "::omnetpp::opp_string \fBipAddress\fP"
.br
.ti -1c
.RI "::omnetpp::opp_string \fBmacAddress\fP"
.br
.ti -1c
.RI "::omnetpp::opp_string \fBage\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "::omnetpp::opp_string \fBinterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class generated from \fCArpTableEntry\&.msg:16\fP by nedtool\&. 
.PP
.nf

//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version\&.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&.  See the
// GNU Lesser General Public License for more details\&.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program\&.  If not, see http://www.gnu.org/licenses/\&.
//
packet \fBArpTableEntry\fP
{
    int identity;
    string protocol;
    string ipAddress;
    string macAddress;
    string age;
    int type;
    string interface;
}
.fi
.PP
 
.PP
Definition at line 50 of file ArpTableEntry_m\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArpTableEntry::ArpTableEntry (const char * name = \fCnullptr\fP, short kind = \fC0\fP)"

.SS "ArpTableEntry::ArpTableEntry (const \fBArpTableEntry\fP & other)"

.PP
Definition at line 188 of file ArpTableEntry_m\&.cc\&.
.SS "ArpTableEntry::~ArpTableEntry ()\fC [virtual]\fP"

.PP
Definition at line 193 of file ArpTableEntry_m\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBArpTableEntry\fP* ArpTableEntry::dup () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 73 of file ArpTableEntry_m\&.h\&.
.SS "const char * ArpTableEntry::getAge () const\fC [virtual]\fP"

.PP
Definition at line 280 of file ArpTableEntry_m\&.cc\&.
.SS "int ArpTableEntry::getIdentity () const\fC [virtual]\fP"

.PP
Definition at line 240 of file ArpTableEntry_m\&.cc\&.
.SS "const char * ArpTableEntry::getInterface () const\fC [virtual]\fP"

.PP
Definition at line 300 of file ArpTableEntry_m\&.cc\&.
.SS "const char * ArpTableEntry::getIpAddress () const\fC [virtual]\fP"

.PP
Definition at line 260 of file ArpTableEntry_m\&.cc\&.
.SS "const char * ArpTableEntry::getMacAddress () const\fC [virtual]\fP"

.PP
Definition at line 270 of file ArpTableEntry_m\&.cc\&.
.SS "const char * ArpTableEntry::getProtocol () const\fC [virtual]\fP"

.PP
Definition at line 250 of file ArpTableEntry_m\&.cc\&.
.SS "int ArpTableEntry::getType () const\fC [virtual]\fP"

.PP
Definition at line 290 of file ArpTableEntry_m\&.cc\&.
.SS "\fBArpTableEntry\fP & ArpTableEntry::operator= (const \fBArpTableEntry\fP & other)"

.PP
Definition at line 197 of file ArpTableEntry_m\&.cc\&.
.SS "bool ArpTableEntry::operator== (const \fBArpTableEntry\fP &)\fC [protected]\fP"

.SS "void ArpTableEntry::parsimPack (omnetpp::cCommBuffer * b) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 216 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::parsimUnpack (omnetpp::cCommBuffer * b)\fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 228 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setAge (const char * age)\fC [virtual]\fP"

.PP
Definition at line 285 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setIdentity (int identity)\fC [virtual]\fP"

.PP
Definition at line 245 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setInterface (const char * interface)\fC [virtual]\fP"

.PP
Definition at line 305 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setIpAddress (const char * ipAddress)\fC [virtual]\fP"

.PP
Definition at line 265 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setMacAddress (const char * macAddress)\fC [virtual]\fP"

.PP
Definition at line 275 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setProtocol (const char * protocol)\fC [virtual]\fP"

.PP
Definition at line 255 of file ArpTableEntry_m\&.cc\&.
.SS "void ArpTableEntry::setType (int type)\fC [virtual]\fP"

.PP
Definition at line 295 of file ArpTableEntry_m\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "::omnetpp::opp_string ArpTableEntry::age\fC [protected]\fP"

.PP
Definition at line 57 of file ArpTableEntry_m\&.h\&.
.SS "int ArpTableEntry::identity\fC [protected]\fP"

.PP
Definition at line 53 of file ArpTableEntry_m\&.h\&.
.SS "::omnetpp::opp_string ArpTableEntry::interface\fC [protected]\fP"

.PP
Definition at line 59 of file ArpTableEntry_m\&.h\&.
.SS "::omnetpp::opp_string ArpTableEntry::ipAddress\fC [protected]\fP"

.PP
Definition at line 55 of file ArpTableEntry_m\&.h\&.
.SS "::omnetpp::opp_string ArpTableEntry::macAddress\fC [protected]\fP"

.PP
Definition at line 56 of file ArpTableEntry_m\&.h\&.
.SS "::omnetpp::opp_string ArpTableEntry::protocol\fC [protected]\fP"

.PP
Definition at line 54 of file ArpTableEntry_m\&.h\&.
.SS "int ArpTableEntry::type\fC [protected]\fP"

.PP
Definition at line 58 of file ArpTableEntry_m\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
