.TH "ClientMemory.cc" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientMemory.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <omnetpp\&.h>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'ClientMemory\&.h'\fP
.br
\fC#include 'MacTableEntry_m\&.h'\fP
.br
\fC#include 'QuantumKeyEntry_m\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDefine_Module\fP (\fBClientMemory\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Define_Module (\fBClientMemory\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
