.TH "ClientProcessor.cc" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientProcessor.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <omnetpp\&.h>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <random>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'ClientProcessor\&.h'\fP
.br
\fC#include 'ClientMemory\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDefine_Module\fP (\fBClientProcessor\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Define_Module (\fBClientProcessor\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
