.TH "ClientFilterDiagonal" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientFilterDiagonal
.SH SYNOPSIS
.br
.PP
.PP
Inherits cSimpleModule\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinitialize\fP () override"
.br
.ti -1c
.RI "virtual void \fBhandleMessage\fP (cMessage *msg) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ClientFilterDiagonal\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void ClientFilterDiagonal::handleMessage (cMessage * msg)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 28 of file ClientFilterDiagonal\&.cc\&.
.SS "void ClientFilterDiagonal::initialize ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 24 of file ClientFilterDiagonal\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
