.TH "md__r_e_a_d_m_e" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- A Novel Multiple Access Quantum Key Distribution Network for Secure Communication 

.PP
.RS 4
An investigation into the use of laws of quantum physics and communication protocols to enable multiple clients to exchange quantum keys in a LAN environment for secure communication\&. 
.RE
.PP
.SS "Keywords : Quantum Key Distribution, Communication Protocols, Security, Quantum Physics, Local Area Network (LAN)"
.PP
.PP
.PP
.PP
.PP
 
