.TH "Processor.cc" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Processor.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <omnetpp\&.h>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'SwitchMemory\&.h'\fP
.br
\fC#include 'MacTableEntry_m\&.h'\fP
.br
\fC#include 'QuantumSubInterfaceBinding_m\&.h'\fP
.br
\fC#include 'ArpTableEntry_m\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProcessor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDefine_Module\fP (\fBProcessor\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "cModule * \fBtModule\fP"
.br
.ti -1c
.RI "\fBSwitchMemory\fP * \fBswitchMemory\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Define_Module (\fBProcessor\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBSwitchMemory\fP* switchMemory"

.PP
Definition at line 20 of file Processor\&.cc\&.
.SS "cModule* tModule"

.PP
Definition at line 19 of file Processor\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
