.TH "QuantumKeyEntry_m.h" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuantumKeyEntry_m.h
.SH SYNOPSIS
.br
.PP
\fC#include <omnetpp\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuantumKeyEntry\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__QUANTUMKEYENTRY_M_H\fP"
.br
.ti -1c
.RI "#define \fBMSGC_VERSION\fP   0x0504"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdoParsimPacking\fP (omnetpp::cCommBuffer *b, const \fBQuantumKeyEntry\fP &obj)"
.br
.ti -1c
.RI "void \fBdoParsimUnpacking\fP (omnetpp::cCommBuffer *b, \fBQuantumKeyEntry\fP &obj)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __QUANTUMKEYENTRY_M_H"

.PP
Definition at line 9 of file QuantumKeyEntry_m\&.h\&.
.SS "#define MSGC_VERSION   0x0504"

.PP
Definition at line 14 of file QuantumKeyEntry_m\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void doParsimPacking (omnetpp::cCommBuffer * b, const \fBQuantumKeyEntry\fP & obj)\fC [inline]\fP"

.PP
Definition at line 68 of file QuantumKeyEntry_m\&.h\&.
.SS "void doParsimUnpacking (omnetpp::cCommBuffer * b, \fBQuantumKeyEntry\fP & obj)\fC [inline]\fP"

.PP
Definition at line 69 of file QuantumKeyEntry_m\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
