.TH "SwitchMemory.h" 3 "Tue Sep 17 2019" "Multiaccess QKD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SwitchMemory.h
.SH SYNOPSIS
.br
.PP
\fC#include <omnetpp\&.h>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'MacTableEntry_m\&.h'\fP
.br
\fC#include 'QuantumSubInterfaceBinding_m\&.h'\fP
.br
\fC#include 'SessionStateEntry_m\&.h'\fP
.br
\fC#include 'ArpTableEntry_m\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSwitchMemory\fP"
.br
.RI "Class to hold the objects in memory\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBQueryType\fP { \fBmacAddress\fP, \fBqMacAddres\fP, \fBinterface\fP, \fBqInterface\fP }"
.br
.RI "Enumerator to query the MAC Address Table\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBQueryType\fP"

.PP
Enumerator to query the MAC Address Table\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fImacAddress \fP\fP
.TP
\fB\fIqMacAddres \fP\fP
.TP
\fB\fIinterface \fP\fP
.TP
\fB\fIqInterface \fP\fP
.PP
Definition at line 36 of file SwitchMemory\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiaccess QKD from the source code\&.
